# Generated by Django 3.2 on 2022-01-15 20:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220115_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttranslation',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='post_body'),
        ),
    ]
