# Generated by Django 3.2 on 2022-01-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_posttranslation_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttranslation',
            name='description',
            field=models.CharField(blank=True, max_length=180, verbose_name='post_description'),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='title',
            field=models.CharField(max_length=120, verbose_name='post_title'),
        ),
    ]
